// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdesujumjrfjexpkfzud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkZXN1anVtanJmamV4cGtmenVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTQ4MzUsImV4cCI6MjA2NzQ3MDgzNX0.WaSmXypZ3ljigYBL0dkvJJafgovbgDlUoh6Iiw06RaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});